import hashlib
import streamlit as st

from .services.graph import evaluate_candidate_interview, run_interview_graph
from .services.transcription import transcribe_audio
from .state import (
    clear_current_mode,
    get_audio_mode,
    get_candidate_evaluation,
    get_current_mode,
    get_langgraph_last_run_info,
    get_live_interview_questions,
    get_summary_qa_text,
    reset_audio_state,
    set_audio_mode,
    set_candidate_evaluation,
    set_current_mode,
    set_generated_interview_data,
)
from .styles import load_css









APP_TITLE = "Interview Portal — AI Technical Screening"


def render_header() -> None:

    st.markdown(
        """
        <div class="app-hero-header">
            <div class="hero-left">
                <div class="hero-logo-box">⚡</div>
                <div class="hero-title-group">
                    <h1>AI Technical Interview Portal</h1>
                    <p>Intelligent technical screening, live audio simulation & Q&A analysis</p>
                </div>
            </div>
            <div class="hero-status-pill">
                <span class="status-dot"></span>
                <span>System Ready</span>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_input_section() -> tuple[str, str, str]:
    st.markdown('<div class="config-card">', unsafe_allow_html=True)
    st.markdown('<div class="config-section-title">⚙️ Configuration & Agent Setup</div>', unsafe_allow_html=True)
    st.markdown('<div class="section-grid">', unsafe_allow_html=True)

    st.markdown('<div class="section-label">📝 User Instructions</div>', unsafe_allow_html=True)
    instructions = st.text_area(
        "User Instructions",
        value=(
            "default instruction:prepare one hour technical interview questions "
            "and answers along with follow up interview questions and answers "
            "for below requirement:"
        ),
        height=85,
        label_visibility="collapsed",
        key="user_instructions",
    )

    st.markdown('<div class="section-label">💼 Job Requirement</div>', unsafe_allow_html=True)
    job_requirement = st.text_area(
        "Job Requirement",
        placeholder="Paste technical job requirement, skills, or tech stack here...",
        height=85,
        label_visibility="collapsed",
        key="job_requirement",
    )

    st.markdown('<div class="section-label">🔑 Google Gemini API Key</div>', unsafe_allow_html=True)
    gemini_api_key = st.text_input(
        "Google Gemini API Key",
        type="password",
        placeholder="Enter your Gemini API Key here (e.g., AIzaSy...)",
        help="Your key is held strictly in browser session memory and is never saved to disk or loaded from .env.",
        key="gemini_api_key",
        label_visibility="collapsed",
    )

    st.markdown("</div>", unsafe_allow_html=True)

    # LangGraph Execution Control
    st.markdown('<div style="margin-top: 14px;"></div>', unsafe_allow_html=True)
    gen_col1, _ = st.columns([2.5, 3.5])
    with gen_col1:
        if st.button(
            "⚡ Generate Interview Q&A with LangGraph",
            key="btn_generate_langgraph",
            type="primary",
            use_container_width=True,
        ):
            if not gemini_api_key or not gemini_api_key.strip():
                st.warning("⚠️ Please provide your Google Gemini API Key above to generate interview questions.")
                st.toast("⚠️ Google Gemini API Key is required!", icon="🔑")
            else:
                try:
                    with st.spinner("🤖 Running LangGraph Workflow with Google Gemini..."):
                        graph_result = run_interview_graph(
                            instructions=instructions,
                            job_requirement=job_requirement,
                            selected_agent="Gemini (Google)",
                            api_key=gemini_api_key.strip(),
                        )
                        qa_text = graph_result.get("extracted_qa_text", "")
                        questions_text = graph_result.get("extracted_questions_text", "")

                        set_generated_interview_data(
                            qa_text=qa_text,
                            questions_text=questions_text,
                            agent_name="Gemini (Google)",
                            evaluator_notes=None,
                        )
                        st.toast("✓ LangGraph (Google Gemini) completed! Q&A loaded.", icon="⚡")
                except Exception as e:
                    st.error(f"❌ LangGraph Generation Failed: {e}")
                    st.toast(f"❌ Error: {e}", icon="⚠️")

    # Display LangGraph Execution Status
    last_run = get_langgraph_last_run_info()
    if last_run:
        agent_used = last_run.get("agent", "Gemini (Google)")
        st.caption(f"✓ Active Q&A generated by LangGraph ({agent_used})")

    st.markdown("</div>", unsafe_allow_html=True)
    return instructions, job_requirement, "Gemini (Google)", gemini_api_key.strip() if gemini_api_key else ""


def render_action_buttons() -> None:
    current_mode = get_current_mode()
    left, right = st.columns([1, 1], gap="medium")

    with left:
        sum_btn_type = "primary" if current_mode == "summary" else "secondary"
        if st.button(
            "📋 Summarize Interview Questions and Answers",
            key="summary_button",
            use_container_width=True,
            type=sum_btn_type,
        ):
            set_current_mode("summary")
            st.rerun()

    with right:
        int_btn_type = "primary" if current_mode == "interview" else "secondary"
        if st.button(
            "🎙️ Give Live Interview",
            key="interview_button",
            use_container_width=True,
            type=int_btn_type,
        ):
            set_current_mode("interview")
            st.rerun()

    st.markdown("</div>", unsafe_allow_html=True)


def render_dynamic_inputs(
    instructions: str = "",
    job_requirement: str = "",
    llm: str = "Gemini (Google)",
    gemini_api_key: str = "",
) -> None:

    current_mode = get_current_mode()

    if not current_mode:
        return

    st.markdown("---")

    if current_mode == "summary":
        with st.container(border=True):
            col_content, col_remove = st.columns([13, 1])

            with col_remove:
                if st.button("✕", key="remove_summary", help="Close summary workspace"):
                    clear_current_mode()
                    st.rerun()

            with col_content:
                st.markdown(
                    '<div class="card-header-badge badge-summary">📋 Technical Q&A Summary Workspace</div>',
                    unsafe_allow_html=True,
                )
                st.caption("✨ Interview questions & answers generated and formatted for summarization:")
                qa_ver = st.session_state.get("summary_qa_version", 0)
                current_qa = get_summary_qa_text(default_value="")
                st.text_area(
                    "Interview Questions & Answers",
                    value=current_qa,
                    placeholder="Click '⚡ Generate Interview Q&A with LangGraph' above to dynamically create questions and answers for this role...",
                    height=450,
                    key=f"summary_text_input_{qa_ver}",
                )

    elif current_mode == "interview":
        audio_mode = get_audio_mode()

        with st.container(border=True):
            col_content, col_remove = st.columns([13, 1])

            with col_remove:
                if st.button("✕", key="remove_interview", help="Close interview session"):
                    clear_current_mode()
                    st.rerun()

            with col_content:
                st.markdown(
                    '<div class="card-header-badge badge-interview">🎙️ Live Interview Session</div>',
                    unsafe_allow_html=True,
                )
                st.caption("✨ List of interview questions generated by AI based on your instructions and job requirement:")
                int_ver = st.session_state.get("interview_questions_version", 0)
                current_questions = get_live_interview_questions(default_value="")
                st.text_area(
                    "List of Interview Questions",
                    value=current_questions,
                    placeholder="Click '⚡ Generate Interview Q&A with LangGraph' above to dynamically load the list of interview questions based on your instructions and job requirement...",
                    height=320,
                    key=f"interview_text_input_{int_ver}",
                )




                st.markdown('<div class="audio-controls-label">🎧 Audio Response Options:</div>', unsafe_allow_html=True)
                btn_col1, btn_col2, btn_col3, _ = st.columns([1.4, 1.4, 1.0, 1.4])

                with btn_col1:
                    rec_btn_type = "primary" if audio_mode == "record" else "secondary"
                    if st.button(
                        "🎙️ Record Microphone",
                        key="btn_rec_interview",
                        type=rec_btn_type,
                        use_container_width=True,
                    ):
                        set_audio_mode("record")
                        st.rerun()

                with btn_col2:
                    up_btn_type = "primary" if audio_mode == "upload" else "secondary"
                    if st.button(
                        "📁 Upload Audio File",
                        key="btn_up_interview",
                        type=up_btn_type,
                        use_container_width=True,
                    ):
                        set_audio_mode("upload")
                        st.rerun()

                with btn_col3:
                    if st.button(
                        "🔄 Reset",
                        key="btn_reset_audio",
                        type="secondary",
                        use_container_width=True,
                        help="Reset audio recording, upload, and transcribed text",
                    ):
                        reset_audio_state()
                        st.toast("✓ Audio session reset!", icon="🔄")
                        st.rerun()

                audio_v = st.session_state.get("audio_session_version", 0)

                if audio_mode == "record":
                    st.markdown('<div class="audio-section-box">', unsafe_allow_html=True)
                    st.caption("🎙️ Click the microphone button to record your response. When you stop recording, speech is automatically converted to text and evaluated:")
                    recorded_audio = st.audio_input(
                        "Record Audio",
                        key=f"audio_rec_input_{audio_v}",
                        label_visibility="collapsed",
                    )
                    if recorded_audio is not None:
                        st.audio(recorded_audio)
                        audio_bytes = recorded_audio.getvalue()
                        audio_hash = hashlib.sha256(audio_bytes).hexdigest()

                        if audio_hash != st.session_state.get("last_processed_audio_hash"):
                            with st.spinner("🎙️ Audio recording stopped. Converting speech to text with whisper.cpp..."):
                                res = transcribe_audio(audio_bytes, model_name="base.en")
                                trans_text = res.get("text", "").strip()
                                st.session_state["latest_transcribed_text"] = trans_text
                                st.session_state["last_processed_audio_hash"] = audio_hash

                            if trans_text:
                                with st.spinner("🤖 Evaluating candidate answers & calculating selection probability..."):
                                    eval_res = evaluate_candidate_interview(
                                        transcript=trans_text,
                                        job_requirement=job_requirement,
                                        instructions=instructions,
                                        selected_agent=llm,
                                        api_key=gemini_api_key,
                                    )
                                    set_candidate_evaluation(eval_res)
                                    st.toast(
                                        f"✓ Candidate evaluated: {eval_res.get('eligibility_status')} ({eval_res.get('selection_probability')}%)",
                                        icon="📊",
                                    )
                            st.rerun()

                    latest_text = st.session_state.get("latest_transcribed_text")
                    if latest_text:
                        st.markdown(
                            f"""
                            <div class="transcript-card">
                                <div class="transcript-header">
                                    <span class="transcript-badge">🎙️ Transcribed Audio Text</span>
                                </div>
                                <div class="transcript-text-display">{latest_text}</div>
                            </div>
                            """,
                            unsafe_allow_html=True,
                        )

                        # Candidate Performance & Selection Evaluation Card
                        eval_data = get_candidate_evaluation()
                        if eval_data:
                            eligibility = eval_data.get("eligibility_status", "ELIGIBLE FOR SELECTION")
                            probability = eval_data.get("selection_probability", 85)
                            report_text = eval_data.get("report_text", "")

                            badge_class = "eligibility-badge-eligible"
                            if "NOT" in eligibility.upper() or "REJECT" in eligibility.upper():
                                badge_class = "eligibility-badge-rejected"
                            elif "BORDERLINE" in eligibility.upper() or "CONDITIONAL" in eligibility.upper():
                                badge_class = "eligibility-badge-borderline"

                            st.markdown(
                                f"""
                                <div class="candidate-eval-card">
                                    <div class="candidate-eval-header">
                                        <div class="{badge_class}">
                                            <span>⚖️ {eligibility}</span>
                                        </div>
                                        <div class="prob-pill">
                                            <span>🎯 Selection Probability: {probability}%</span>
                                        </div>
                                    </div>
                                    <div class="eval-report-content">
                                        {report_text}
                                    </div>
                                </div>
                                """,
                                unsafe_allow_html=True,
                            )

                    st.markdown("</div>", unsafe_allow_html=True)

                elif audio_mode == "upload":
                    st.markdown('<div class="audio-section-box">', unsafe_allow_html=True)
                    st.caption("📁 Choose or drop an audio file (WAV, MP3, M4A, OGG, AAC, FLAC, WEBM):")
                    uploaded_audio = st.file_uploader(
                        "Upload Audio File",
                        type=["wav", "mp3", "m4a", "ogg", "flac", "aac", "webm"],
                        key=f"audio_up_input_{audio_v}",
                        label_visibility="collapsed",
                    )
                    if uploaded_audio is not None:
                        st.audio(uploaded_audio)
                        upload_bytes = uploaded_audio.getvalue()
                        upload_hash = hashlib.sha256(upload_bytes).hexdigest()

                        if upload_hash != st.session_state.get("last_processed_upload_hash"):
                            with st.spinner("📁 Converting uploaded audio to text with whisper.cpp..."):
                                res = transcribe_audio(upload_bytes, model_name="base.en")
                                trans_text = res.get("text", "").strip()
                                st.session_state["latest_transcribed_text"] = trans_text
                                st.session_state["last_processed_upload_hash"] = upload_hash

                            if trans_text:
                                with st.spinner("🤖 Evaluating candidate answers & calculating selection probability..."):
                                    eval_res = evaluate_candidate_interview(
                                        transcript=trans_text,
                                        job_requirement=job_requirement,
                                        instructions=instructions,
                                        selected_agent=llm,
                                        api_key=gemini_api_key,
                                    )
                                    set_candidate_evaluation(eval_res)
                                    st.toast(
                                        f"✓ Candidate evaluated: {eval_res.get('eligibility_status')} ({eval_res.get('selection_probability')}%)",
                                        icon="📊",
                                    )
                            st.rerun()

                    latest_text = st.session_state.get("latest_transcribed_text")
                    if latest_text:
                        st.markdown(
                            f"""
                            <div class="transcript-card">
                                <div class="transcript-header">
                                    <span class="transcript-badge">📁 Transcribed Audio Text</span>
                                </div>
                                <div class="transcript-text-display">{latest_text}</div>
                            </div>
                            """,
                            unsafe_allow_html=True,
                        )

                        # Candidate Performance & Selection Evaluation Card
                        eval_data = get_candidate_evaluation()
                        if eval_data:
                            eligibility = eval_data.get("eligibility_status", "ELIGIBLE FOR SELECTION")
                            probability = eval_data.get("selection_probability", 85)
                            report_text = eval_data.get("report_text", "")

                            badge_class = "eligibility-badge-eligible"
                            if "NOT" in eligibility.upper() or "REJECT" in eligibility.upper():
                                badge_class = "eligibility-badge-rejected"
                            elif "BORDERLINE" in eligibility.upper() or "CONDITIONAL" in eligibility.upper():
                                badge_class = "eligibility-badge-borderline"

                            st.markdown(
                                f"""
                                <div class="candidate-eval-card">
                                    <div class="candidate-eval-header">
                                        <div class="{badge_class}">
                                            <span>⚖️ {eligibility}</span>
                                        </div>
                                        <div class="prob-pill">
                                            <span>🎯 Selection Probability: {probability}%</span>
                                        </div>
                                    </div>
                                    <div class="eval-report-content">
                                        {report_text}
                                    </div>
                                </div>
                                """,
                                unsafe_allow_html=True,
                            )

                    st.markdown("</div>", unsafe_allow_html=True)


def render_app() -> None:
    st.set_page_config(
        page_title=APP_TITLE,
        page_icon="⚡",
        layout="wide",
        initial_sidebar_state="collapsed",
    )

    load_css()
    render_header()

    instructions, job_requirement, llm, gemini_api_key = render_input_section()

    st.session_state["request_context"] = {
        "instructions": instructions,
        "job_requirement": job_requirement,
        "llm_agent": llm,
        "gemini_api_key": gemini_api_key,
    }

    render_action_buttons()
    render_dynamic_inputs(
        instructions=instructions,
        job_requirement=job_requirement,
        llm=llm,
        gemini_api_key=gemini_api_key,
    )




